config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :messages, only: :create
  resources :chats, only: [:create, :new, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  after_create :add_title
  has_many :messages
  belongs_to :user1, class_name: 'User'
	belongs_to :user2, class_name: 'User'
	validates :user1, :user2, presence: true
  validates :index_str, presence: true, uniqueness: true
  
	private
    
    def add_title
      self.title = "#{self.user1.name}/#{self.user2.name}"
      self.save
    end
    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
  default_scope { order(created_at: :asc) }
  validates :content, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	has_many :chats_initiated, class_name: 'Chat', foreign_key: 'user1_id'
	has_many :chats_invited,	 class_name: 'Chat', foreign_key: 'user2_id'
	before_save { self.email = email.downcase }
	validates :name,  	 presence: true, length: { maximum: 50 , minimum: 3 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, 	 presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false },
																																 format:		 { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { minimum: 6 } 
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please, Log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :logged_in_user
  
  def show
    @chat = Chat.find(params[:id])
    @messages = @chat.messages
    @message = Message.new
  end
  
  def new
    @chat = Chat.new
    @users = User.all
    @message = current_user.messages.build
  end
  
  def create
    @chat = Chat.new
    @chat.user1_id = params[:user1]
    @chat.user2_id = params[:user2]
    if params[:user1] > params[:user2]
      @chat.index_str = "#{params[:user1]}-#{params[:user2]}"
    else
      @chat.index_str = "#{params[:user2]}-#{params[:user1]}"
    end
    @index = @chat.index_str
    if @chat.save
      @chat.messages.create!(content: params[:content], user_id: current_user.id)
      flash[:success] = "Chat created Successfully."
      redirect_to @chat
    else
      @chat_existing = Chat.find_by(index_str: @index)
      @chat_existing.messages.create!(content: params[:content], user_id: current_user.id)
      redirect_to @chat_existing
    end
  end
  
  private
  
    #def chat_params
    #  params.require(:chat).permit(:user1_id, :user2_id)
    #end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :logged_in_user
	
	def create
		@message = Message.new
		@message.content = params[:message][:content]
		@message.user_id = params[:user_id]
		@message.chat_id = params[:chat_id]
		if @message.save
			chatupdated = Chat.find(params[:chat_id])
			chatupdated.updated_at = DateTime.now
			chatupdated.save
			redirect_back(fallback_location: root_path)
		else
			flash[:danger] = "Message can't be empty!"
			redirect_back(fallback_location: root_path)
		end
	end
	
	private
	
		#def message_params
		#	params.require(:message).permit(:content, :user_id, :chat_id)
		#end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,       only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    $VisitedUser = params[:id]
    if current_user?(@user)
      if @user.chats_initiated.any?
        @chats = @user.chats_initiated
        @chats += @user.chats_invited if @user.chats_invited.any?
      elsif @user.chats_invited.any?
        @chats = @user.chats_invited
      else
        @chats = []
      end
      @chats = @chats.uniq.sort_by(&:updated_at).reverse unless @chats.blank?
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to chat_the_f_up."
      log_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end
	
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def current_user?(user)
		user == current_user
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/chats/new.html.erb
<%= form_for @chat do |f| %>

	<%= render 'shared/error_messages', object: f.object %>

	<%= hidden_field_tag :user1, current_user.id %>

	<%= label_tag :user2, "Select User:" %>
	<%= select_tag :user2, options_from_collection_for_select(@users, "id", "name", $VisitedUser) %>
	
	<%= text_area_tag :content, nil, :required => true %>
	
	<%= f.submit "Send" %>

<% end %>

app/views/chats/show.html.erb
<h1><%= @chat.title %></h1>

<%= render @messages %>

<%= render 'messages/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
    <p>
      <%= link_to "Home", root_url %>
      <% if logged_in? %>
        <%= link_to "Profile", current_user %>
        <%= link_to "Users", users_url %>
      <% end %>
    </p>
    
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    
    <%= yield %>
    
    <% if logged_in? %>
      <p>---------</p>
      <p>
        <%= link_to "Settings", edit_user_path(current_user) %>
      </p>
      <p>
        <%= link_to "Log out", logout_path, method: :delete %>
      </p>
    <% end %>
    
    <%= debug(params) if Rails.env.development? %>
    <%= debug(session[:user_id]) if Rails.env.development? %>
    <%= debug($VisitedUser) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>

	<%= hidden_field_tag :chat_id, @chat.id %>
	
	<%= hidden_field_tag :user_id, current_user.id %>

	<%= f.text_area :content %>
	
	<%= f.submit "Send" %>

<% end %>

app/views/messages/_message.html.erb
<p>
	<%= link_to gravatar_for(message.user, size: 20), user_path(message.user) %>
	<%= message.user.name %>: <%= message.content %>
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Welcome to Chatter1</h1>

<% if logged_in? %>
	<%= link_to "Profile", current_user %>
<% else %>
	<p><%= link_to "Sign up", new_user_path %></p>
	<p><%= link_to "Log in" , login_url  %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Settings</h1>

<%= form_for @user do |f| %>

	<%= render 'shared/error_messages', object: f.object %>
	
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>
	
	<p>
		<%= f.submit "Update" %>
	</p>
	
  <div class="gravatar_edit">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>

	<%= render 'shared/error_messages', object: f.object %>
	
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>
	
	<p>
		<%= f.submit "Sign up" %>
	</p>

<% end %>

app/views/users/show.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

<%= link_to "Send a message", new_chat_url %>

<% if current_user?(@user) %>
  <% if @chats.try(:any?) %>
    <% @chats.each do |c| %>
      <p>
        <%= link_to gravatar_for(c.user1, size: 20), user_path(c.user1) %>
        <%= link_to gravatar_for(c.user2, size: 20), user_path(c.user2) %>
        <%= link_to c.title, chat_path(c) %>
      </p>
    <% end %>
  <% end %>
<% end %>